### ISSUE TITLE
Flavor issues tracker

### ISSUE THREAD

**Issue by armanddidierjean** [aeecleclair/Titan#193]
- [x] use distinct url scheme for Titan flavors
 - [x] use three environment variables for Titan flavors (ex: `DEV_HOST`, `ALPHA_HOST`, `PROD_HOST`)
 - [x] use images associated with Titan flavor
