### ISSUE TITLE
Refacto issue tracker

### ISSUE THREAD

**Issue by armanddidierjean** [aeecleclair/Titan#194]
### Calendar
- [x] We can't scroll to the next month

### Events
- [x] The padding is strange
<img width="400" alt="Capture d’écran 2023-11-06 à 20 40 33" src="https://github.com/aeecleclair/Titan/assets/95971503/55dad944-1a9b-4c53-b37b-c58eff4901f3">

- [ ] when creating a day long event, there is a timezone issue

### Advert
 - [ ] we can not add an image when adding an advert and we can not validate without adding one

### Centralisation
 - [ ] some icon are not displayed correctly (DSI, Commuz)

**Comment by Petitoto** [comment]
` we can not add an image when adding an advert and we can not validate without adding one`
`when creating a day long event, there is a timezone issue`
I'm unable to reproduce these issue (tested on Android and web)

` some icon are not displayed correctly (DSI, Commuz)`
Not related to refacto
